export const classicStrategies = Object.freeze([
  {
    id: "ma-cross",
    name: "Moving Average Cross",
    family: "trend",
    features: {
      functions: ["ta.sma", "ta.ema", "ta.rma", "ta.wma", "ta.crossover", "ta.crossunder"],
      keywords: ["fast", "slow", "ma", "ema", "sma", "trend"],
      regex: ["\\bfast(Ma|MA|Ema|EMA|Sma|SMA)?\\b", "\\bslow(Ma|MA|Ema|EMA|Sma|SMA)?\\b"],
    },
    entryLogic: "Fast moving average crosses above the slow moving average.",
    exitLogic: "Fast moving average crosses below the slow moving average; optional short entry for two-way tests.",
    typicalParams: [
      { name: "fastLength", values: [10, 20, 50], effect: "Shorter reacts earlier but creates more false crosses." },
      { name: "slowLength", values: [50, 100, 200], effect: "Longer follows regime changes more slowly but filters more noise." },
      { name: "tradeDirection", values: ["Long Only", "Both"], effect: "Long-only often avoids shorting persistent equity uptrends." },
    ],
    worksWhen: "Markets trend long enough after a crossover for momentum to continue.",
    failsWhen: "Range-bound markets where averages repeatedly cross without follow-through.",
    pineSkeleton: [
      "longEntry = ta.crossover(fast, slow)",
      "longExit = ta.crossunder(fast, slow)",
      "shortEntry = ta.crossunder(fast, slow)",
      "shortExit = ta.crossover(fast, slow)",
    ].join("\n"),
    pitfalls: [
      "Very slow parameters can leave only a few trades, making backtests look cleaner than they are.",
      "Do not add extra smoothing without explaining the added lag.",
    ],
  },
  {
    id: "macd-cross",
    name: "MACD Signal Cross",
    family: "momentum",
    features: {
      functions: ["ta.macd", "ta.crossover", "ta.crossunder"],
      keywords: ["macd", "signal", "hist", "histogram"],
      regex: ["\\bmacd(Line)?\\b", "\\bsignal(Line)?\\b"],
    },
    entryLogic: "MACD line crosses above the signal line; optional histogram confirmation.",
    exitLogic: "MACD line crosses below the signal line, or momentum turns negative.",
    typicalParams: [
      { name: "fastLength", values: [8, 12, 16], effect: "Shorter reacts faster but whipsaws more." },
      { name: "slowLength", values: [21, 26, 34], effect: "Longer smooths trend but lags reversals." },
      { name: "signalLength", values: [5, 9, 12], effect: "Shorter exits earlier; longer waits for stronger confirmation." },
    ],
    worksWhen: "Momentum persists after moving-average convergence/divergence turns up.",
    failsWhen: "Sideways markets with repeated zero-line churn.",
    pineSkeleton: [
      "longEntry = ta.crossover(macdLine, signalLine)",
      "longExit = ta.crossunder(macdLine, signalLine)",
      "shortEntry = ta.crossunder(macdLine, signalLine)",
      "shortExit = ta.crossover(macdLine, signalLine)",
    ].join("\n"),
    pitfalls: [
      "Do not trade histogram color changes as if they were confirmed signal-line crosses.",
      "Zero-line filters reduce churn but can miss early reversals.",
    ],
  },
  {
    id: "bollinger-mean-reversion",
    name: "Bollinger Band Mean Reversion",
    family: "mean-reversion",
    features: {
      functions: ["ta.bb", "ta.stdev", "ta.sma", "ta.crossover", "ta.crossunder"],
      keywords: ["bollinger", "basis", "upper", "lower", "band", "deviation"],
      regex: ["\\bupper(Band)?\\b", "\\blower(Band)?\\b", "\\bbasis\\b"],
    },
    entryLogic: "Price recovers upward through the lower band after an oversold excursion.",
    exitLogic: "Price reaches or crosses the basis/upper band, depending on aggressiveness.",
    typicalParams: [
      { name: "length", values: [14, 20, 30], effect: "Longer bands are slower and less sensitive to recent volatility." },
      { name: "mult", values: [1.5, 2, 2.5], effect: "Wider bands trade less often and demand more extreme deviations." },
      { name: "exitBand", values: ["basis", "upper"], effect: "Basis exits sooner; upper exits wait for stronger mean reversion." },
    ],
    worksWhen: "Prices revert after volatility pushes them outside a statistically wide band.",
    failsWhen: "Strong trends that walk the band and keep making new extremes.",
    pineSkeleton: [
      "longEntry = ta.crossover(close, lower)",
      "longExit = ta.crossunder(close, basis) or ta.crossover(close, upper)",
      "shortEntry = ta.crossunder(close, upper)",
      "shortExit = ta.crossover(close, basis) or ta.crossunder(close, lower)",
    ].join("\n"),
    pitfalls: [
      "Band touches are not reversals by themselves; prefer a cross back inside the band.",
      "Breakout versions invert the logic, so identify whether the script is reversion or trend-following.",
    ],
  },
  {
    id: "rsi-reversion",
    name: "RSI Threshold Reversion",
    family: "mean-reversion",
    features: {
      functions: ["ta.rsi", "ta.crossover", "ta.crossunder", "hline"],
      keywords: ["rsi", "overbought", "oversold"],
      regex: ["\\b70\\b", "\\b30\\b", "\\b80\\b", "\\b20\\b"],
    },
    entryLogic: "RSI crosses upward out of oversold territory.",
    exitLogic: "RSI crosses downward from overbought territory or returns to a neutral threshold.",
    typicalParams: [
      { name: "length", values: [7, 14, 21], effect: "Shorter RSI is more responsive and noisier." },
      { name: "oversold", values: [20, 30, 40], effect: "Lower thresholds demand more extreme selloffs before entry." },
      { name: "overbought", values: [60, 70, 80], effect: "Higher thresholds hold longer but can give back gains." },
    ],
    worksWhen: "Markets oscillate and overreact before reverting toward the mean.",
    failsWhen: "Persistent trends where oversold can stay oversold or overbought can stay overbought.",
    pineSkeleton: [
      "longEntry = ta.crossover(rsiValue, oversold)",
      "longExit = ta.crossunder(rsiValue, overbought)",
      "shortEntry = ta.crossunder(rsiValue, overbought)",
      "shortExit = ta.crossover(rsiValue, oversold)",
    ].join("\n"),
    pitfalls: [
      "RSI divergence drawings are discretionary; only convert explicit numeric signals.",
      "Use confirmed bar values when the original script updates intrabar.",
    ],
  },
  {
    id: "donchian-breakout",
    name: "Donchian Channel Breakout",
    family: "breakout",
    features: {
      functions: ["ta.highest", "ta.lowest", "ta.crossover", "ta.crossunder"],
      keywords: ["donchian", "channel", "highest", "lowest", "breakout", "upper", "lower"],
      regex: ["\\bhighest\\(", "\\blowest\\(", "\\bchannel\\b"],
    },
    entryLogic: "Price breaks above the prior upper channel.",
    exitLogic: "Price breaks below the lower channel or a shorter exit channel.",
    typicalParams: [
      { name: "entryLength", values: [20, 55, 100], effect: "Longer channels require more significant breakouts." },
      { name: "exitLength", values: [10, 20, 55], effect: "Shorter exits cut failed breakouts sooner." },
      { name: "tradeDirection", values: ["Long Only", "Both"], effect: "Two-way tests suit futures/FX better than equity-only regimes." },
    ],
    worksWhen: "Breakouts continue after range expansion.",
    failsWhen: "False breakouts in choppy markets with no volatility expansion.",
    pineSkeleton: [
      "upper = ta.highest(high, entryLength)[1]",
      "lower = ta.lowest(low, exitLength)[1]",
      "longEntry = ta.crossover(close, upper)",
      "longExit = ta.crossunder(close, lower)",
    ].join("\n"),
    pitfalls: [
      "Use the prior channel value (`[1]`) for breakout triggers to avoid comparing against a channel that includes the current bar.",
      "Breakout systems need enough trades across markets before trusting a single strong equity curve.",
    ],
  },
]);
